### ISSUE TITLE
Memleak

### ISSUE THREAD

**Issue by xacrimon** [jonhoo/bustle#3]
Trying to run with some bigger table sizes. It looks like bustle is leaking memory and getting OOM killed. Any insight on this?

**Comment by jonhoo** [comment]
Hmm, there is a very small (<1kb) intentional leak in every invocation of `run`:
https://github.com/jonhoo/bustle/blob/8837244930fbfe055a561431b28cbcf6e8ca9a10/src/lib.rs#L321
It could be fixed easy enough by replacing it with `Arc` I suppose, though there's no way that's causing your OOM killing.

Bustle _does_ allocate the entire key set for the workload in memory for each run, which can get large if you are running with very large initial capacity or an ops factor significantly above 1.0, so maybe that's what's causing you to run out of memory?

**Comment by xacrimon** [comment]
What's wierd is that this only happens after a few runs. I running the mutex hashmap bench with an ops of 1.0 and a capacity of 2^27. It runs fine with 1-4 thread but dies at 5 threads. It looks to go up per thread but I'm not sure. I have 16 GiB of ram btw.

**Comment by jonhoo** [comment]
That's very strange indeed. I don't know of a reason why that would happen. You could try running with the address sanitizer maybe?
https://github.com/jonhoo/flurry/blob/7b27a79cfa502c054583ad7ca52358e24306782b/azure-pipelines.yml#L72
(or the leak sanitizer, though I've found it less reliable):
https://github.com/jonhoo/flurry/blob/7b27a79cfa502c054583ad7ca52358e24306782b/azure-pipelines.yml#L74-L91

**Comment by xacrimon** [comment]
I'm going to run sanitizers now but something is very wrong. htop shows the benchmark program as 4.0T on virtual memory, that happens instantly once started. Memory usage seems to go up by about 2 GiB per thread.

**Comment by xacrimon** [comment]
Looks like the keyset is being replicated for each thread.

**Comment by jonhoo** [comment]
Found it! Give me a sec.

**Comment by xacrimon** [comment]
Also, on another note. Prefill still panics with bustle 0.4.

**Comment by jonhoo** [comment]
The `Mutex<HashMap>` bench runs just fine for me with `prefill_fraction(0.5)` on 0.4?

**Comment by jonhoo** [comment]
Fixed in 0.4.1

**Comment by xacrimon** [comment]
Nevermind it works now. Thank you
